#!/usr/bin/env python

import os
import sys
import commands

trash_path =  os.environ['HOME'] + "/" + os.environ['TRASH'] + "/"

def move_old(dest) :
  global reps
  global tics
  newdest = dest + "_old"
  if (os.path.exists(newdest)) :
    move_old(newdest)

  commands.getoutput("mv " + dest + " " + newdest)
           

for s in sys.argv[1:]:
  # first, does it exist? If not, bail

  if not os.path.exists(s) :
    print s, " : not found"
    continue

  # remove trailing slashes
  s = s.rstrip('/')
  pathname = os.path.dirname(s)
  if (pathname == trash_path) : #  This doesn't work right... revisit
    print s + " already trashed "
    exit
    
  basename = os.path.basename(s)
  newname = trash_path + basename

  if os.path.exists(newname) :
    move_old(newname)
    
  print s + commands.getoutput("mv " + s + " " + newname)

	

