#!/bin/bash

file1=$1
file2=$2
if [[ ! -e $file1 ]]; then
    echo "File $file1 does not exist";
    exit 1;
fi;

if [[ ! -e $file2 ]]; then
    echo "File $file2 does not exist";
    exit 1;
fi;

jdiff.py $file1 $file2

if [[ $? != 0 ]] ; then
    $HOME/bin/jdiff.py --diff-tool kdiff3 $file1 $file2
else
    echo "Files are JSON identical"
fi

