#!/bin/bash

FILE=""

for x in $@; do 
    if [[ $x =~ \.$ ]]; then x="$x*"; fi
    NAME=`cygpath -m $x`;
    FILE="$FILE $NAME"
done

echo "doing $FILE"


/cygdrive/c/emacs/emacs-25.1/bin/emacs.exe $FILE

#/usr/bin/emacs-w32.exe  $FILE


